language: java
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base
jdk:
- oraclejdk8
env:
  matrix:
  - CLOUD=mandatory LARGE=true
  - CLOUD=todo 
  - CLOUD=false LARGE=true
  - DATAFLOW_RUNNER=SparkPipelineRunner CLOUD=false SPARK=false
  global:
  #gradle needs this
  - TERM=dumb
  #google cloud stuff
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GCLOUD=$HOME/gcloud/google-cloud-sdk/bin 
  - CLOUDSDK_PYTHON_SITEPACKAGES=1 
  - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/servicekey.json
  #hellbender specific variables
  - HELLBENDER_TEST_INPUTS=gs://hellbender/test/resources/
  - HELLBENDER_TEST_STAGING=gs://hellbender/test/staging/
  - HELLBENDER_TEST_PROJECT=broad-dsde-dev
  #coveralls repo token
  - secure: RA4LKD82cW+0xPayPVAWSpYqJu5uoPcz7oXXYtYNVuilFmS8PGYx0g/BXs4QMvQsGMt6aMLN8m7lMAPN5XTH/8JSeM3VmQ3mdpgNdP+p3CVlwrapZ2lTq27Wb/E8J1CGEHOg76z716t//FUElyC/gdhS+tfBmXk3YanM5fMXEHs=
  #google API key
  - secure: GyC3Th11Gryeokc2UucWTS/Rc6AB+4ZRcSzpmLliTEtrCvDt+sXPxTH9z7GKiwqz0Ep91TTot/G8fDdSIUa+50itV1WKGDtkoRAvkG6Mt7bWm+5Cy6ZbPhktX+dWR5ks/9R8EBlJ5oiC6WkMcqlwZ90DftcHYOOF5+4ToCp7HzM=
matrix:
  fast_finish: true
  allow_failures:
    - env: DATAFLOW_RUNNER=SparkPipelineRunner CLOUD=false SPARK=false
    - env: CLOUD=todo
cache:
  directories:
  - ~/.gradle
  - $HOME/gcloud/
  - src/test/resources/large/

before_install:
#download large files
- if [ $LARGE == "true" ]; then bash scripts/install_git_lfs.sh; fi
#setup google stuff
- openssl aes-256-cbc -K $encrypted_29f3b7c4d8c3_key -iv $encrypted_29f3b7c4d8c3_iv
  -in resources_for_CI/servicekey.json.enc -out servicekey.json -d
- scripts/install_gcloud.sh
- printf 'y\n' | $GCLOUD/gcloud components update app
- $GCLOUD/gcloud config set project broad-dsde-dev
- $GCLOUD/gcloud auth activate-service-account --key servicekey.json
- R --version
after_success:
- gradle jacocoTestReport coveralls
after_failure:
- dmesg | tail -100
after_script:
- $GCLOUD/gcloud components -q update gsutil
- REPORT_PATH=$TRAVIS_BRANCH_$TRAVIS_JOB_NUMBER
- $GCLOUD/gsutil -m cp -z html -z js -z xml -z css -r build/reports/tests gs://hellbender/test/build_reports/$REPORT_PATH/
- echo "See the test report at https://storage.googleapis.com/hellbender/test/build_reports/$REPORT_PATH/tests/index.html"
